services:
  code-server:
    image: ghcr.io/ezazulhaq/custom-code-server:latest
    restart: unless-stopped
    expose:
      - 8080
    volumes:
      - code-server-home:/home/coder
      - ${WORKSPACE}:/home/coder/workspace
    environment:
      - PASSWORD=${PASSWORD}
      - TZ=${TZ}
    user: "1000:1000"

volumes:
  code-server-home:
